### Create a new Report

POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Ford",
  "model": "Mustang",
  "year": 1982,
  "mileage": 50000,
  "lng": 45,
  "lat": 45,
  "price": 20000
}

### Approve an existing report

PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for a Toyota Corolla

GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=0&lat=0&mileage=20000&year=1980

### Get an estimate for a Ford Mustang

GET http://localhost:3000/reports?make=Ford&model=Mustang&lng=45&lat=45&mileage=20000&year=1981